[application]

# App (Project) Name
name = "{{Tabaxi}}"

# Dioxus App Default Platform
# desktop, web
# {% if platform == "desktop" %}
# default_platform = "desktop"
# {% else %}
default_platform = "web"
# {% endif %}

# `build` & `serve` dist path
out_dir = "dist"

# resource (public) file folder
asset_dir = "assets"

[web.app]

# HTML title tag content
# title = "{{project-name}}"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
# reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "assets"]

# include `assets` in web platform
[web.resource]

# CSS style file
# {% if styling == "Tailwind" %}
# style = ["tailwind.css"]
# {% else %}
style = ["./main.css"]
# {% endif %}

# Javascript code file
# script = []

[web.resource.dev]

style = ["./main.css"]
# Javascript code file
# serve: [dev-server] only
# script = []
